import Link from "next/link";
import "./globals.css";
import "./mainPage.css";

export const metadata = {
  title: "타이틀 태그에 들어갈 값", // <title> 태그에 들어갈 값
  description: "Generated by create next app", // <meta name="description" content="..." 에 들어갈 값
};

export default function RootLayout({ children }) {
  return (
    <html lang="ko">
      <body>
        <header>
          <h1>
            <Link href={"/"}>🏠</Link>
          </h1>
        </header>
        {children}
      </body>
    </html>
  );
}
