export const metadata = {
  title: "Next.js", // <title> 태그에 들어갈 값
  description: "Generated by create next app", // <meta name="description" content="...">들어갈 값
};

export default function RootLayout({ children }) {
  return (
    <html lang="ko">
      <body>{children}</body>
    </html>
  );
}
